### ISSUE TITLE
package name and groupId for maven

### ISSUE THREAD

**Issue by priitliivak** [nortal/DataBata#21]
Currently the package name for DataBata is eu.databata but we don't actually own that domain.
Currently options are:
* com.nortal.databata - top level ownership can be confirmed
* com.github.databata
* io.github.databata - reserved for projects in github.
* register databata.eu

This is stopping getting DataBata up to Maven Central.

**Comment by maxboiko** [comment]
See on minu poolt ostetud. Peaks juunini veel kehtima. EE ka

**Comment by priitliivak** [comment]
Great, did not know that :+1: 
You can see the status of the request here: https://issues.sonatype.org/browse/OSSRH-13584
