### ISSUE TITLE
Print the default table names for lock, change history and propagation objects

### ISSUE THREAD

**Issue by tonisb** [nortal/DataBata#29]
Currently, if no properties for used tables are defined in the propagator bean, then upon propagation the default values (sys_db_propagator_history, ...) are printed as null since they are defined in the DAO not in the propagator.

It would be good to still see these values printed out.

**Comment by tanelkaar** [comment]
Agree - Defaults should not be defined in DAO layer.

**Comment by tanelkaar** [comment]
Fixed in 195c3ae398972ed96a8cb5fd075c70ab1a0a3b8c
