### ISSUE TITLE
Object directory location parsing as Url fails in case of urlescaped symbols.

### ISSUE THREAD

**Issue by tanelkaar** [nortal/DataBata#30]
Using java.net.URL data type in Propagator.set*Dir methods might seem cool, but URLs tend to escape special symbols (urlencode), which makes it unusable in local file system. For example, tomcat uses number symbols to store context path and application version:
my-app#contextPathInTomcat#applicationVersion.war 

Now after using URL.getPath(), you'll get /my/local/machine/tomcat/webapps/my-app%23contextPathInTomcat%23applicationVersion/WEB-INF/db/views, which is not a valid path.

I propose to use org.springframework.core.io.Resource

**Comment by tanelkaar** [comment]
Fixed in a00838cb4a7c11c4cddf98c29d3b43be6590700c

**Comment by basileus-v** [comment]
I guess this fix breaks file handling in OSGi environment.

**Comment by tanelkaar** [comment]
Adding overloaded methods with URL to PropagatorOsgiInstance would solve the issue? Maybe moving methods with spring Resource to PropagatorSpringInstance in that case too.

**Comment by tanelkaar** [comment]
as setChanges was already implemented that way, should be OK.
